# Generated by Django 3.1.3 on 2021-01-27 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atm_py', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction_dummy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('action', models.CharField(default='username', max_length=200)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atm_py.dataclass')),
            ],
        ),
    ]
