# Generated by Django 3.1.3 on 2021-01-28 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atm_py', '0003_auto_20210128_0903'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Balance_inq',
        ),
    ]
