# Generated by Django 3.1.3 on 2021-01-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance_inq',
            name='balance',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
