# Generated by Django 3.1.3 on 2021-01-28 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210128_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime_field', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('remaining_amount', models.CharField(default=None, max_length=20)),
                ('withdrawl_amount', models.CharField(default=None, max_length=20)),
            ],
        ),
    ]
