# Generated by Django 3.1.3 on 2021-01-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_transactionhistory_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance_inq',
            name='balance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='remaining_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='withdrawl_amount',
            field=models.IntegerField(),
        ),
    ]
